import { Sex, ICharacter } from ".root./data/interface/Character.interface";

interface ICharacterData extends ICharacter {
  anime: string;
}

export const characterList: ICharacterData[] = [
  {
    type: 'main',
    name: 'Kanade Tachibana',
    nameKanji: '立華 かなで',
    avatar: 'https://cdn.myanimelist.net/images/characters/10/289337.jpg',
    sex: Sex.Female,
    anime: 'Angel Beats',
  },
  {
    type: 'main',
    name: 'Yuri Nakamura',
    nameKanji: '仲村 ゆり',
    avatar: 'https://cdn.myanimelist.net/images/characters/7/119951.jpg',
    sex: Sex.Female,
    anime: 'Angel Beats',
  },
  {
    type: 'main',
    name: 'Yui',
    nameKanji: 'ユイ',
    avatar: 'https://cdn.myanimelist.net/images/characters/11/150391.jpg',
    sex: Sex.Female,
    anime: 'Angel Beats',
  },
  {
    type: 'main',
    name: 'Yuzuru Otonashi',
    nameKanji: '音無結弦',
    avatar: 'https://cdn.myanimelist.net/images/characters/16/318156.jpg',
    sex: Sex.Male,
    anime: 'Angel Beats',
  },
  {
    type: 'main',
    name: 'Hideki Hinata',
    nameKanji: '日向秀樹',
    avatar: 'https://cdn.myanimelist.net/images/characters/7/87904.jpg',
    sex: Sex.Male,
    anime: 'Angel Beats',
  },
  {
    type: 'supporting',
    name: 'T.K.',
    nameKanji: 'T.K.',
    avatar: 'https://cdn.myanimelist.net/images/characters/10/91153.jpg',
    sex: Sex.Male,
    anime: 'Angel Beats',
  },
  {
    type: 'supporting',
    name: 'Masami Iwasawa',
    nameKanji: '岩沢 雅美',
    avatar: 'https://cdn.myanimelist.net/images/characters/12/117224.jpg',
    sex: Sex.Female,
    anime: 'Angel Beats',
  },
  {
    type: 'supporting',
    name: 'Ayato Naoi',
    nameKanji: '直井文人',
    avatar: 'https://cdn.myanimelist.net/images/characters/8/101119.jpg',
    sex: Sex.Male,
    anime: 'Angel Beats',
  },
  {
    type: 'supporting',
    name: 'Shiina',
    nameKanji: '椎名',
    avatar: 'https://cdn.myanimelist.net/images/characters/5/96113.jpg',
    sex: Sex.Female,
    anime: 'Angel Beats',
  },
  {
    type: 'supporting',
    name: 'Noda',
    nameKanji: '野田',
    avatar: 'https://cdn.myanimelist.net/images/characters/10/85250.jpg',
    sex: Sex.Male,
    anime: 'Angel Beats',
  },

  {
    type: 'main',
    name: 'Jeanne d\'Arc',
    nameKanji: '-',
    avatar: 'https://cdn.myanimelist.net/images/characters/10/333655.jpg',
    sex: Sex.Female,
    anime: 'Fate/Apocrypha',
  },
  {
    type: 'main',
    name: 'Sieg',
    nameKanji: '-',
    avatar: 'https://cdn.myanimelist.net/images/characters/5/333656.jpg',
    sex: Sex.Male,
    anime: 'Fate/Apocrypha',
  },
  {
    type: 'supporting',
    name: 'Saber',
    nameKanji: '-',
    avatar: 'https://cdn.myanimelist.net/images/characters/6/275276.jpg',
    sex: Sex.Female,
    anime: 'Fate/Apocrypha',
  },
  {
    type: 'supporting',
    name: 'Kuro no Rider',
    nameKanji: '-',
    avatar: 'https://cdn.myanimelist.net/images/characters/7/333308.jpg',
    sex: Sex.Male,
    anime: 'Fate/Apocrypha',
  },
  {
    type: 'supporting',
    name: 'Aka no Saber',
    nameKanji: '-',
    avatar: 'https://cdn.myanimelist.net/images/characters/9/333073.jpg',
    sex: Sex.Female,
    anime: 'Fate/Apocrypha',
  },
  {
    type: 'supporting',
    name: 'Waver Velvet',
    nameKanji: 'ウェイバー・ベルベット',
    avatar: 'https://cdn.myanimelist.net/images/characters/8/126883.jpg',
    sex: Sex.Male,
    anime: 'Fate/Apocrypha',
  },
  {
    type: 'supporting',
    name: 'Aka no Lancer',
    nameKanji: 'ウェイバー・ベルベット',
    avatar: 'https://cdn.myanimelist.net/images/characters/4/333071.jpg',
    sex: Sex.Male,
    anime: 'Fate/Apocrypha',
  },
  {
    type: 'supporting',
    name: 'Merlin',
    nameKanji: 'マーリン',
    avatar: 'https://cdn.myanimelist.net/images/characters/7/349231.jpg',
    sex: Sex.Male,
    anime: 'Fate/Apocrypha',
  },
  {
    type: 'supporting',
    name: 'Aka no Archer',
    nameKanji: '赤のアーチャー',
    avatar: 'https://cdn.myanimelist.net/images/characters/11/333072.jpg',
    sex: Sex.Female,
    anime: 'Fate/Apocrypha',
  },
  {
    type: 'supporting',
    name: 'Shirou Kotomine',
    nameKanji: 'シロウ・コトミネ',
    avatar: 'https://cdn.myanimelist.net/images/characters/13/333654.jpg',
    sex: Sex.Male,
    anime: 'Fate/Apocrypha',
  },
]
